name: check

on: workflow_call

jobs:
  check:
    name: linting, formatting, typing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install uv and Python
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
        with:
          python-version: 3.12
          enable-cache: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Lint Rust
        working-directory: rust
        run: cargo clippy

      - name: Check Rust formatting
        working-directory: rust
        run: cargo fmt --check

      - name: Lint Python
        run: uv run ruff check

      - name: Check Python formatting
        run: uv run ruff format --check

      - name: Validate Python types
        run: uv run basedpyright
