name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install '.[dev]'
    - name: Enforce formatting
      run: |
        ruff format --check pengwann
        ruff format --check tests
    - name: Lint
      run: |
        ruff check pengwann
    - name: Run static type checking
      run: |
        pyright pengwann
    - name: Generate test coverage report
      run: |
        pytest --cov-report xml --cov=pengwann tests
    - name: Publish test coverage report
      uses: paambaati/codeclimate-action@v9.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
