name: continuous integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Sync environment
        run: uv sync

      - name: Lint
        run: |
          uv run ruff check src
          uv run ruff check tests

      - name: Enforce black formatting
        run: |
          uv run ruff format --check src
          uv run ruff format --check tests

      - name: Run static type checking
        run: uv run pyright

      - name: Run test suite
        run: uv run pytest

      - name: Publish test coverage report
        if: github.event_name == 'push'
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
