name: release

on: push

jobs:
  build:
    name: Build distribution
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install build package
      run: |
        python -m pip install build
    - name: Build wheel and source tarball
      run: |
        python -m build
    - name: Store dist packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: Publish dists to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pengwann
    permissions:
      id-token: write
    steps:
    - name: Download dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish dist to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
