name: release

on: push

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install build package
      run: |
        python -m pip install build
    - name: Build wheel and source tarball
      run: |
        python -m build
    - name: Store dist packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: Publish dists to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pengwann
    permissions:
      id-token: write
    steps:
    - name: Download dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish dist to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: Sign the dist and upload release
    needs:
    - publish-to-pypi
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
    - name: Download dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Sign the dists
      uses: sigstore/gh-action-sigstore-python@v3.0.0
      with:
        inputs: |
          ./dist/*.tar.gz
          ./dist/*.whl
    - name: Create GitHub release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release create
        '${{ github.ref_name }}'
        --repo '${{ github.repository }}'
        --notes ""
    - name: Upload artifact signatures
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release upload
        '${{ github.ref_name }}' dist/**
        --repo '${{ github.repository }}'
